# Site settings
name: MatchWorkshop
title: MatchWorkshop - Indie Game Developer Community
email: ycua541@gmail.com
url: https://matchworkshop.github.io/
description: "MatchWorkshop is a society provide indie game developing opportunities."
collections:
- integrations

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: MatchWorkshop Group
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/FTNGDC
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/MatchWorkshop
  - title: github
    url: http://github.com/MatchWorkshop

# Postal address (add as many lines as necessary)
address:
  - line: 

# Credits content
credits: 'A society provide indie game developing opportunities. '

# Build settings
markdown: kramdown
permalink: pretty
